version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      go:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      web-minor-and-patch:
        update-types: [minor, patch]
      web-major:
        update-types: [major]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      docker:
        patterns: ["*"]
